# 글로벌 iOS 플랫폼 버전 설정
platform :ios, '14.0'

# CocoaPods 분석 비활성화
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# 프로젝트 설정
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# 기본 Runner 타겟 설정
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Firebase SDK 버전 설정
  $FirebaseSDKVersion = '10.22.0'

  # 필요한 Pod 의존성 추가
  pod 'GTMSessionFetcher/Core', '~> 3.3'  # MLKit과 호환되는 버전으로 설정
  pod 'GoogleSignIn', '~> 7.1'  # GoogleSignIn의 버전 설정
  pod 'GoogleMLKit/PoseDetection', '~> 6.0.0'  # MLKit PoseDetection 의존성 추가

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
